version: '1'
services:
  frontend:
    image: frontend:1.0
    ports:
      - 5173:80
    env_file:
      - ./frontend/.env
  backend:
    image: backend:1.0
    ports:
      - 4000:4000
    env_file:
      - ./backend/.env

