version: "1"
services:
  frontend:
    image: engmarwen/samsar:frontend-1.0
    ports:
      - 5173:80
    environment:
      API_URL: "http://localhost:4000"
      FIREBASE_API_KEY: "AIzaSyDxxlLzE6XtYske4-XYMqFc68Rj_RxAMEE"
  backend:
    image: engmarwen/samsar:backend-1.0
    ports:
      - 4000:4000
    env_file:
      - ./backend/.env
