version: "1"
services:
  frontend:
#TODO: find a replacement for including the env file (config.js.template)
    image: engmarwen/samsar:frontend-1.0
    ports:
        - 5173:80
  backend:
    image: engmarwen/samsar:backend-1.0
    ports:
      - 4000:4000
    env_file:
      - ./backend/.env
